"""temp data column addition

Revision ID: ca6b00db5b5c
Revises: 195356f66b6a
Create Date: 2025-08-04 19:27:05.183254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = 'ca6b00db5b5c'
down_revision = '195356f66b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_attendee_data', postgresql.JSON(astext_type=Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('temp_attendee_data')

    # ### end Alembic commands ###
